package com.jiacheng.securevault.audit.enums;

public enum AuditAction {
    REGISTER_SUCCESS,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,

    DOCUMENT_UPLOAD_SUCCESS,
    DOCUMENT_PARSE_SUCCESS,
    DOCUMENT_PARSE_FAILURE,
    DOCUMENT_EMBED_SUCCESS,
    DOCUMENT_EMBED_FAILURE,
    DOCUMENT_CHUNK_VIEW,
    DOCUMENT_DELETE_SUCCESS,
    DOCUMENT_DELETE_FAILURE,

    RAG_ASK_SUCCESS,
    RAG_ASK_FAILURE,

    RESOURCE_ACCESS_DENIED,
    FILE_DECRYPT_FAILURE,

    AUDIT_LOG_READ
}
